// Genera `lib/transparencia/registry.generated.ts` empaquetando el contenido de
// `content/transparencia/*.md` como strings TypeScript. Esto mueve la lectura
// del filesystem de runtime a build-time: el bundle resultante no depende de
// `node:fs/promises`, lo que permite que las rutas de /transparencia/
// funcionen en el runtime de Cloudflare Workers (donde el filesystem no está
// disponible).
//
// Ejecutado por `npm run prebuild` y `npm run predev`.

import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(__dirname, "..");
const TRANSPARENCIA_DIR = path.join(ROOT, "content", "transparencia");
const OUT = path.join(ROOT, "lib", "transparencia", "registry.generated.ts");

type RawPieza = { filename: string; raw: string };

async function readPiezas(): Promise<RawPieza[]> {
  const entries = await readdir(TRANSPARENCIA_DIR);
  const files = entries
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort();
  const out: RawPieza[] = [];
  for (const filename of files) {
    const raw = await readFile(path.join(TRANSPARENCIA_DIR, filename), "utf8");
    out.push({ filename, raw });
  }
  return out;
}

function literal(s: string): string {
  return JSON.stringify(s);
}

async function main(): Promise<void> {
  const piezas = await readPiezas();

  const lines: string[] = [
    "// AUTO-GENERATED — do not edit by hand.",
    "// Regenerated by scripts/build-transparencia-registry.ts via npm run prebuild / predev.",
    "// Sources: content/transparencia/*.md",
    "",
    "export type RawPieza = { readonly filename: string; readonly raw: string };",
    "",
    "export const rawPiezas: ReadonlyArray<RawPieza> = [",
    ...piezas.map(
      (p) =>
        `  { filename: ${literal(p.filename)}, raw: ${literal(p.raw)} },`,
    ),
    "];",
    "",
  ];

  await writeFile(OUT, lines.join("\n"), "utf8");
  console.log(
    `Wrote ${path.relative(ROOT, OUT)} (${piezas.length} piezas)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
