// Genera `lib/preguntas/registry.generated.ts` empaquetando el contenido de
// `.observatorio/preguntas/*.md` y `.observatorio/templates/banner-*.md` como
// strings TypeScript. Esto mueve la lectura del filesystem de runtime a
// build-time: el bundle resultante no depende de `node:fs/promises`, lo que
// permite que las rutas del corpus funcionen en el runtime de Cloudflare
// Workers (donde el filesystem no está disponible).
//
// Ejecutado por `npm run prebuild` y `npm run predev`.

import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(__dirname, "..");
const PREGUNTAS_DIR = path.join(ROOT, ".observatorio", "preguntas");
const TEMPLATES_DIR = path.join(ROOT, ".observatorio", "templates");
const OUT = path.join(ROOT, "lib", "preguntas", "registry.generated.ts");

type RawArticulo = { filename: string; raw: string };

async function readPreguntas(): Promise<RawArticulo[]> {
  const entries = await readdir(PREGUNTAS_DIR);
  const files = entries
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort();
  const out: RawArticulo[] = [];
  for (const filename of files) {
    const raw = await readFile(path.join(PREGUNTAS_DIR, filename), "utf8");
    out.push({ filename, raw });
  }
  return out;
}

async function readBanners(): Promise<Record<string, string>> {
  const entries = await readdir(TEMPLATES_DIR);
  const out: Record<string, string> = {};
  for (const filename of entries) {
    const m = filename.match(/^banner-(.+)\.md$/);
    if (!m) continue;
    const estado = m[1];
    const raw = await readFile(path.join(TEMPLATES_DIR, filename), "utf8");
    out[estado] = raw;
  }
  return out;
}

function literal(s: string): string {
  return JSON.stringify(s);
}

async function main(): Promise<void> {
  const preguntas = await readPreguntas();
  const banners = await readBanners();

  const lines: string[] = [
    "// AUTO-GENERATED — do not edit by hand.",
    "// Regenerated by scripts/build-preguntas-registry.ts via npm run prebuild / predev.",
    "// Sources: .observatorio/preguntas/*.md and .observatorio/templates/banner-*.md",
    "",
    "export type RawArticulo = { readonly filename: string; readonly raw: string };",
    "",
    "export const rawArticulos: ReadonlyArray<RawArticulo> = [",
    ...preguntas.map(
      (p) =>
        `  { filename: ${literal(p.filename)}, raw: ${literal(p.raw)} },`,
    ),
    "];",
    "",
    "export const rawBanners: Readonly<Record<string, string>> = {",
    ...Object.entries(banners).map(
      ([estado, raw]) => `  ${literal(estado)}: ${literal(raw)},`,
    ),
    "};",
    "",
  ];

  await writeFile(OUT, lines.join("\n"), "utf8");
  console.log(
    `Wrote ${path.relative(ROOT, OUT)} (${preguntas.length} artículos, ${Object.keys(banners).length} banners)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
