// Genera `lib/transparencia/registry.generated.ts` empaquetando el contenido de
// `content/transparencia/*.md` como strings TypeScript y, ADICIONALMENTE, el
// cuerpo markdown pre-renderizado a HTML usando los mismos `markdownComponents`
// que usaría runtime. Esto mueve el parseo de `react-markdown` + `remark-gfm`
// de runtime (cada request) a build-time (una vez por pieza). El runtime solo
// inyecta el HTML pre-renderizado con `dangerouslySetInnerHTML`.
//
// Ejecutado por `npm run prebuild` y `npm run predev`.

import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import React from "react";
import { renderToString } from "react-dom/server";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { markdownComponents } from "../lib/preguntas/markdown";
import { sanitizePrerenderedHtml } from "./sanitize-prerendered";

const ROOT = path.resolve(__dirname, "..");
const TRANSPARENCIA_DIR = path.join(ROOT, "content", "transparencia");
const OUT = path.join(ROOT, "lib", "transparencia", "registry.generated.ts");

type RawPieza = { filename: string; raw: string; html: string };

function renderMarkdownToHtml(content: string): string {
  const rendered = renderToString(
    React.createElement(
      ReactMarkdown,
      { remarkPlugins: [remarkGfm], components: markdownComponents },
      content,
    ),
  );
  return sanitizePrerenderedHtml(rendered);
}

async function readPiezas(): Promise<RawPieza[]> {
  const entries = await readdir(TRANSPARENCIA_DIR);
  const files = entries
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort();
  const out: RawPieza[] = [];
  for (const filename of files) {
    const raw = await readFile(path.join(TRANSPARENCIA_DIR, filename), "utf8");
    const parsed = matter(raw);
    const html = renderMarkdownToHtml(parsed.content);
    out.push({ filename, raw, html });
  }
  return out;
}

function literal(s: string): string {
  return JSON.stringify(s);
}

async function main(): Promise<void> {
  const piezas = await readPiezas();

  const lines: string[] = [
    "// AUTO-GENERATED — do not edit by hand.",
    "// Regenerated by scripts/build-transparencia-registry.ts via npm run prebuild / predev.",
    "// Sources: content/transparencia/*.md",
    "// `html` is pre-rendered by react-markdown + remark-gfm + markdownComponents",
    "// at build-time; runtime injects it with dangerouslySetInnerHTML.",
    "",
    "export type RawPieza = {",
    "  readonly filename: string;",
    "  readonly raw: string;",
    "  readonly html: string;",
    "};",
    "",
    "export const rawPiezas: ReadonlyArray<RawPieza> = [",
    ...piezas.map(
      (p) =>
        `  { filename: ${literal(p.filename)}, raw: ${literal(p.raw)}, html: ${literal(p.html)} },`,
    ),
    "];",
    "",
  ];

  await writeFile(OUT, lines.join("\n"), "utf8");
  console.log(
    `Wrote ${path.relative(ROOT, OUT)} (${piezas.length} piezas, html pre-rendered)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
