// Genera `lib/preguntas/registry.generated.ts` empaquetando el contenido de
// `.observatorio/preguntas/*.md` y `.observatorio/templates/banner-*.md` como
// strings TypeScript Y, ADICIONALMENTE, el cuerpo markdown pre-renderizado a
// HTML usando los mismos `markdownComponents` que usaría runtime. Esto mueve
// el parseo de `react-markdown` + `remark-gfm` de runtime (cada request) a
// build-time (una vez por artículo/banner). El runtime solo inyecta el HTML
// pre-renderizado con `dangerouslySetInnerHTML`.
//
// Para artículos: el cuerpo se pre-procesa (strip de banner marker, primer
// H1 y blockquote de marcas temporales) ANTES de renderizar.
// Para banners: se extrae la sección "Copy canónico" antes de renderizar.
//
// Ejecutado por `npm run prebuild` y `npm run predev`.

import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import React from "react";
import { renderToString } from "react-dom/server";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { markdownComponents } from "../lib/preguntas/markdown";
import { stripAllForArticulo } from "../lib/preguntas/strip";
import { extractCanonicalCopy } from "../lib/preguntas/banner";

const ROOT = path.resolve(__dirname, "..");
const PREGUNTAS_DIR = path.join(ROOT, ".observatorio", "preguntas");
const TEMPLATES_DIR = path.join(ROOT, ".observatorio", "templates");
const OUT = path.join(ROOT, "lib", "preguntas", "registry.generated.ts");

type RawArticulo = { filename: string; raw: string; body_html: string };

function renderMarkdownToHtml(content: string): string {
  return renderToString(
    React.createElement(
      ReactMarkdown,
      { remarkPlugins: [remarkGfm], components: markdownComponents },
      content,
    ),
  );
}

async function readPreguntas(): Promise<RawArticulo[]> {
  const entries = await readdir(PREGUNTAS_DIR);
  const files = entries
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort();
  const out: RawArticulo[] = [];
  for (const filename of files) {
    const raw = await readFile(path.join(PREGUNTAS_DIR, filename), "utf8");
    const parsed = matter(raw);
    const cleaned = stripAllForArticulo(parsed.content);
    const body_html = renderMarkdownToHtml(cleaned);
    out.push({ filename, raw, body_html });
  }
  return out;
}

async function readBanners(): Promise<Record<string, string>> {
  const entries = await readdir(TEMPLATES_DIR);
  const out: Record<string, string> = {};
  for (const filename of entries) {
    const m = filename.match(/^banner-(.+)\.md$/);
    if (!m) continue;
    const estado = m[1];
    const raw = await readFile(path.join(TEMPLATES_DIR, filename), "utf8");
    const copy = extractCanonicalCopy(raw, "Copy canónico");
    out[estado] = renderMarkdownToHtml(copy);
  }
  return out;
}

function literal(s: string): string {
  return JSON.stringify(s);
}

async function main(): Promise<void> {
  const preguntas = await readPreguntas();
  const banners = await readBanners();

  const lines: string[] = [
    "// AUTO-GENERATED — do not edit by hand.",
    "// Regenerated by scripts/build-preguntas-registry.ts via npm run prebuild / predev.",
    "// Sources: .observatorio/preguntas/*.md and .observatorio/templates/banner-*.md",
    "// `body_html` (artículos) y `rawBanners` (banners) están pre-renderizados",
    "// por react-markdown + remark-gfm + markdownComponents al build; runtime",
    "// inyecta con dangerouslySetInnerHTML.",
    "",
    "export type RawArticulo = {",
    "  readonly filename: string;",
    "  readonly raw: string;",
    "  readonly body_html: string;",
    "};",
    "",
    "export const rawArticulos: ReadonlyArray<RawArticulo> = [",
    ...preguntas.map(
      (p) =>
        `  { filename: ${literal(p.filename)}, raw: ${literal(p.raw)}, body_html: ${literal(p.body_html)} },`,
    ),
    "];",
    "",
    "export const rawBanners: Readonly<Record<string, string>> = {",
    ...Object.entries(banners).map(
      ([estado, html]) => `  ${literal(estado)}: ${literal(html)},`,
    ),
    "};",
    "",
  ];

  await writeFile(OUT, lines.join("\n"), "utf8");
  console.log(
    `Wrote ${path.relative(ROOT, OUT)} (${preguntas.length} artículos, ${Object.keys(banners).length} banners, pre-rendered)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
