// Genera `lib/transparencia/registry.generated.ts` empaquetando el contenido de
// `content/transparencia/*.md` como strings TypeScript y, ADICIONALMENTE, el
// cuerpo markdown pre-renderizado a HTML usando los mismos `markdownComponents`
// que usaría runtime. Esto mueve el parseo de `react-markdown` + `remark-gfm`
// de runtime (cada request) a build-time (una vez por pieza). El runtime solo
// inyecta el HTML pre-renderizado con `dangerouslySetInnerHTML`.
//
// Ejecutado por `npm run prebuild` y `npm run predev`.

import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import React from "react";
import { renderToString } from "react-dom/server";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { markdownComponents } from "../lib/preguntas/markdown";
import { sanitizePrerenderedHtml } from "./sanitize-prerendered";

const ROOT = path.resolve(__dirname, "..");
const TRANSPARENCIA_DIR = path.join(ROOT, "content", "transparencia");
const OUT = path.join(ROOT, "lib", "transparencia", "registry.generated.ts");

type SummaryHtml = {
  pregunta: string;
  precios: string;
  contratos: string;
  frontera: string;
};

type BodyChunk = {
  html: string;
  chartAfter: "V2" | "V3" | "V4" | null;
};

type RawPieza = {
  filename: string;
  raw: string;
  html: string;
  bodyChunks: BodyChunk[];
  summaryHtml: SummaryHtml;
};

// Split renderized body HTML at chart sentinels. Each sentinel `[chart:VX]`
// on its own markdown line becomes a `<p class="…">[chart:VX]</p>` paragraph
// after react-markdown + markdownComponents. We find those exact paragraphs
// and split the body into chunks, dropping the sentinel paragraph and
// labeling which chart goes after each chunk.
function splitBodyAtSentinels(html: string): BodyChunk[] {
  const sentinelRegex =
    /<p class="font-sans[^"]*">\[chart:(V[234])\]<\/p>/g;
  const chunks: BodyChunk[] = [];
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = sentinelRegex.exec(html)) !== null) {
    chunks.push({
      html: html.slice(last, m.index),
      chartAfter: m[1] as "V2" | "V3" | "V4",
    });
    last = m.index + m[0].length;
  }
  chunks.push({ html: html.slice(last), chartAfter: null });
  return chunks;
}

function renderMarkdownToHtml(content: string): string {
  const rendered = renderToString(
    React.createElement(
      ReactMarkdown,
      { remarkPlugins: [remarkGfm], components: markdownComponents },
      content,
    ),
  );
  return sanitizePrerenderedHtml(rendered);
}

function requireString(
  v: unknown,
  filename: string,
  field: string,
): string {
  if (typeof v !== "string" || v.length === 0) {
    throw new Error(
      `Frontmatter inválido en ${filename}: campo "${field}" debe ser string no vacío`,
    );
  }
  return v;
}

function renderSummaryHtml(
  data: Record<string, unknown>,
  filename: string,
): SummaryHtml {
  const summary = data.summary;
  if (!summary || typeof summary !== "object") {
    throw new Error(
      `Frontmatter inválido en ${filename}: campo "summary" debe ser objeto`,
    );
  }
  const o = summary as Record<string, unknown>;
  return {
    pregunta: renderMarkdownToHtml(
      requireString(o.pregunta, filename, "summary.pregunta"),
    ),
    precios: renderMarkdownToHtml(
      requireString(o.precios, filename, "summary.precios"),
    ),
    contratos: renderMarkdownToHtml(
      requireString(o.contratos, filename, "summary.contratos"),
    ),
    frontera: renderMarkdownToHtml(
      requireString(o.frontera, filename, "summary.frontera"),
    ),
  };
}

async function readPiezas(): Promise<RawPieza[]> {
  const entries = await readdir(TRANSPARENCIA_DIR);
  const files = entries
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort();
  const out: RawPieza[] = [];
  for (const filename of files) {
    const raw = await readFile(path.join(TRANSPARENCIA_DIR, filename), "utf8");
    const parsed = matter(raw);
    const html = renderMarkdownToHtml(parsed.content);
    const bodyChunks = splitBodyAtSentinels(html);
    const summaryHtml = renderSummaryHtml(
      parsed.data as Record<string, unknown>,
      filename,
    );
    out.push({ filename, raw, html, bodyChunks, summaryHtml });
  }
  return out;
}

function literal(s: string): string {
  return JSON.stringify(s);
}

async function main(): Promise<void> {
  const piezas = await readPiezas();

  const lines: string[] = [
    "// AUTO-GENERATED — do not edit by hand.",
    "// Regenerated by scripts/build-transparencia-registry.ts via npm run prebuild / predev.",
    "// Sources: content/transparencia/*.md",
    "// `html` is pre-rendered by react-markdown + remark-gfm + markdownComponents",
    "// at build-time; runtime injects it with dangerouslySetInnerHTML.",
    "",
    "export type RawSummaryHtml = {",
    "  readonly pregunta: string;",
    "  readonly precios: string;",
    "  readonly contratos: string;",
    "  readonly frontera: string;",
    "};",
    "",
    "export type RawBodyChunk = {",
    '  readonly html: string;',
    '  readonly chartAfter: "V2" | "V3" | "V4" | null;',
    "};",
    "",
    "export type RawPieza = {",
    "  readonly filename: string;",
    "  readonly raw: string;",
    "  readonly html: string;",
    "  readonly bodyChunks: ReadonlyArray<RawBodyChunk>;",
    "  readonly summaryHtml: RawSummaryHtml;",
    "};",
    "",
    "export const rawPiezas: ReadonlyArray<RawPieza> = [",
    ...piezas.map((p) => {
      const chunks = p.bodyChunks
        .map(
          (c) =>
            `    { html: ${literal(c.html)}, chartAfter: ${c.chartAfter === null ? "null" : literal(c.chartAfter)} },`,
        )
        .join("\n");
      return `  { filename: ${literal(p.filename)}, raw: ${literal(p.raw)}, html: ${literal(p.html)}, bodyChunks: [\n${chunks}\n  ], summaryHtml: { pregunta: ${literal(p.summaryHtml.pregunta)}, precios: ${literal(p.summaryHtml.precios)}, contratos: ${literal(p.summaryHtml.contratos)}, frontera: ${literal(p.summaryHtml.frontera)} } },`;
    }),
    "];",
    "",
  ];

  await writeFile(OUT, lines.join("\n"), "utf8");
  console.log(
    `Wrote ${path.relative(ROOT, OUT)} (${piezas.length} piezas, html pre-rendered)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
